// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXProject4
{
    internal sealed partial class Vsix
    {
        public const string Id = "VSIXProject4.ff8a0656-7e55-41ab-843e-d62defa7ce0d";
        public const string Name = "AlignProperties";
        public const string Description = @"Aligns C# properties to columns";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Oliver Abraham";
        public const string Tags = "";
    }
}
