// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXProject4
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string VisualStudioCodeReadabilityString = "bd6a68b7-c2d5-43b0-bae1-534aafa50e4f";
        public static Guid VisualStudioCodeReadability = new Guid(VisualStudioCodeReadabilityString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int AlignCSharpProperties = 0x0100;
    }
}